steps:
# WORDPRESS
# build
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/ply-platform-353b/cloud-one-docker-images/wordpress', '.' ]
  dir: 'srcs/requirements/wordpress'
  id: 'wordpress'
# push
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'europe-west1-docker.pkg.dev/ply-platform-353b/cloud-one-docker-images/wordpress']
  waitFor: ['wordpress']

# NGINX
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/ply-platform-353b/cloud-one-docker-images/nginx', '.' ]
  dir: 'srcs/requirements/nginx'
  id: 'nginx'
# push
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'europe-west1-docker.pkg.dev/ply-platform-353b/cloud-one-docker-images/nginx']
  waitFor: ['nginx']


# MARIADB
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/ply-platform-353b/cloud-one-docker-images/mariadb', '.' ]
  dir: 'srcs/requirements/mariadb'
  id: 'mariadb'
# push
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'europe-west1-docker.pkg.dev/ply-platform-353b/cloud-one-docker-images/mariadb']
  waitFor: ['mariadb']