steps:
# WORDPRESS
# build
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/ply-plaform-353b/cloud-one-docker-images/wordpress', '-f', 'srcs/requirements/wordpress/Dockerfile', '.' ]
# push
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'europe-west1-docker.pkg.dev/ply-plaform-353b/cloud-one-docker-images/wordpress']
# NGINX
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/ply-plaform-353b/cloud-one-docker-images/nginx', '-f', 'srcs/requirements/nginx/Dockerfile', '.' ]
# push
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'europe-west1-docker.pkg.dev/ply-plaform-353b/cloud-one-docker-images/nginx']
# MARIADB
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/ply-plaform-353b/cloud-one-docker-images/mariadb', '-f', 'srcs/requirements/mariadb/Dockerfile', '.' ]
# push
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'europe-west1-docker.pkg.dev/ply-plaform-353b/cloud-one-docker-images/mariadb']