steps:
# WORDPRESS
# build
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/ply-platform-353b/cloud-one-docker-images/wordpress/wordpress/', '.' ]
  dir: 'srcs/requirements/wordpress'
# push
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'europe-west1-docker.pkg.dev/ply-platform-353b/cloud-one-docker-images/wordpress/wordpress']
  waitFor: ['-']
# NGINX
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/ply-platform-353b/cloud-one-docker-images/nginx/nginx', '.' ]
  dir: 'srcs/requirements/nginx'
# push
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'europe-west1-docker.pkg.dev/ply-platform-353b/cloud-one-docker-images/nginx/nginx']
  waitFor: ['-']
# MARIADB
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/ply-platform-353b/cloud-one-docker-images/mariadb/mariadb', '.' ]
  dir: 'srcs/requirements/mariadb'
# push
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'europe-west1-docker.pkg.dev/ply-platform-353b/cloud-one-docker-images/mariadb/mariadb']
  waitFor: ['-']